### ISSUE TITLE
sentencepiece training : dataset does not load correctly

### ISSUE THREAD

**Issue by lecoqnicolas** [google/sentencepiece#1100]
On a 60 cores, 512GB instance, I have the following issue with the sentencepiece trainer on a 180M dataset : only 4M sentences randomly load and training goes on.

I use the following options : 
--train_extremely_large_corpus True 
--shuffle input_sentences True 
--character_coverage 0.9999 
--byte_fallback True 
--vocab_size 32000 
--model_prefix /mydir/sentencepiece 
--input_sentence_size : 2*source_size (i use moses format)

Can anyone help me with this? The script is fully functional on a 2*10M research dataset, but I do not figure how I could train a proper tokenizer from many trained on "edible" subsets.
```
sentencepiece_trainer.cc(77) LOG(INFO) Starts training with :
trainer_spec {
  input: C:\Users\Administrator\Locomotive\run\en_fr-1.5\src-train.txt
  input: C:\Users\Administrator\Locomotive\run\en_fr-1.5\tgt-train.txt
  input_format:
  model_prefix: C:\Users\Administrator\Locomotive\run\en_fr-1.5/sentencepiece
  model_type: UNIGRAM
  vocab_size: 32000
  self_test_sample_size: 0
  character_coverage: 0.9999
  input_sentence_size: 180124580
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter:
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars:
  byte_fallback: 1
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  Ôüç
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
denormalizer_spec {}
trainer_interface.cc(351) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(183) LOG(INFO) Loading corpus: C:\Users\Administrator\Locomotive\run\en_fr-1.5\src-train.txt
trainer_interface.cc(145) LOG(INFO) Loaded 1000000 lines
trainer_interface.cc(183) LOG(INFO) Loading corpus: C:\Users\Administrator\Locomotive\run\en_fr-1.5\tgt-train.txt
trainer_interface.cc(145) LOG(INFO) Loaded 2000000 lines
trainer_interface.cc(145) LOG(INFO) Loaded 3000000 lines
trainer_interface.cc(145) LOG(INFO) Loaded 4000000 lines
trainer_interface.cc(122) LOG(WARNING) Too many sentences are loaded! (4132797), which may slow down training.
trainer_interface.cc(124) LOG(WARNING) Consider using --input_sentence_size=<size> and --shuffle_input_sentence=true.
trainer_interface.cc(127) LOG(WARNING) They allow to randomly sample <size> sentences from the entire corpus.
trainer_interface.cc(407) LOG(INFO) Loaded all 4132797 sentences
```
