### ISSUE TITLE
Pip install does not accept symbol flags

### ISSUE THREAD

**Issue by Fhrozen** [google/sentencepiece#409]
Hi, there

Thank you very much for such a nice work.
I am being working with sentencepiece installed from pip and just realized that it does not accept `--user_defined_symbols` or `--control_symbols`. Showing the following error:
```
sentencepiece_trainer.cc(116) LOG(INFO) Running command: --input=data/lang_char/input.txt --vocab_size=2000 --model_type=unigram --model_prefix=data/lang_char/train_si284_unigram2000 '--user_defined_symbols=<*IN*>,<*MR.*>,<NOISE>' --input_sentence_size=100000000
Traceback (most recent call last):
  File "/export/db/transf/egs/wsj/asr2/../../../utils/spm_train", line 17, in <module>
    spm.SentencePieceTrainer.Train(" ".join(map(shlex.quote, sys.argv[1:])))
OSError: Not found: unknown field name "'--user_defined_symbols" in TrainerSpec.
```
if I just print the options i got:
```
TrainerSpec {
  input_format: 
  model_prefix: 
  model_type: UNIGRAM
  vocab_size: 8000
  self_test_sample_size: 0
  character_coverage: 0.9995
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  treat_whitespace_as_suffix: 0
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇ 
}
NormalizerSpec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv: 
}
```

and does not show the required flags, but if I test `spm_train.py` built from the source it displays the flags:
```
   --use_all_vocab (If set to true, use all tokens as vocab. Valid for word/char models.)  type: bool  default: false
   --user_defined_symbols (comma separated list of user defined symbols)  type: string  default: 
```
I am wondering if the .so file probably has not been updated and so the flags are not available. 

BTW, I was trying to make a custom installation for python but it requires to be installed with sudo. I will be nice if there is available and custom installation flag (?).
