### ISSUE TITLE
Training spm fails even with 500GB memory

### ISSUE THREAD

**Issue by pluiez** [google/sentencepiece#704]
I'm trying to train a spm model from a large multilingual corpus, including Portuguese, Arabic and English texts. The corpus contains 15,000,000 sentences in total, with 50 million for each of the three languages.

I understand that limiting input_sentence_size to a small value might enables successful training, but I'm wondering how did Google successfully train their spm model with 250,000 pieces over 100 languages on the much larger mC4 corpus? 500GB memory is not even enough for training 150M sentences.

The following is my training spec.

```
trainer_spec {                                                                                                                                                                                                                          
  input: joint-50000000.txt
  input_format:
  model_prefix: spm.50M.model
  model_type: UNIGRAM
  vocab_size: 80000
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 128
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  treat_whitespace_as_suffix: 0
  required_chars:
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 1
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
```
