### ISSUE TITLE
about running spm.SentencePieceTrainer.Train()?

### ISSUE THREAD

**Issue by Joll123** [google/sentencepiece#770]
when I run the following code, it is not running. and get no any information.

import sentencepiece as spm
spm.SentencePieceTrainer.Train('--input=/Users/jinhonglong/Desktop/transformer/iwslt2016/prepro/train --model_prefix=m --vocab_size=1000')
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by taku910** [comment]
It is hard for us to know the cause of this error. Probably you are training models from extremely large data. If so, data sampling might work.

**Comment by nghuyong** [comment]
I meet the same problem with `normalization_rule_name=identity`

here is the log 
```
sentencepiece_trainer.cc(78) LOG(INFO) Starts training with :                                                                                                                                                                                           
trainer_spec {                                                                                                                                                                                                                                          
  input_format: text                                                                                                                                                                                                                                    
  model_prefix:                                                                                                                                                                                                                                         
  model_type: BPE                                                                                                                                                                                                                                       
  vocab_size: 32000                                                                                                                                                                                                                                     
  self_test_sample_size: 0                                                                                                                                                                                                                              
  character_coverage: 0.999                                                                                                                                                                                                                             
  input_sentence_size: 0                                                                                                                                                                                                                                
  shuffle_input_sentence: 1                                                                                                                                                                                                                             
  seed_sentencepiece_size: 1000000                                                                                                                                                                                                                      
  shrinking_factor: 0.75                                                                                                                                                                                                                                
  max_sentence_length: 65535                                                                                                                                                                                                                            
  num_threads: 16                                                                                                                                                                                                                                       
  num_sub_iterations: 2                                                                                                                                                                                                                                 
  max_sentencepiece_length: 32                                                                                                                                                                                                                          
  split_by_unicode_script: 1                                                                                                                                                                                                                            
  split_by_number: 1                                                                                                                                                                                                                                    
  split_by_whitespace: 1                                                                                                                                                                                                                                
  split_digits: 1                                                                                                                                                                                                                                       
  pretokenization_delimiter:                                                                                                                                                                                                                            
  treat_whitespace_as_suffix: 0                                                                                                                                                                                                                         
  allow_whitespace_only_pieces: 1                                                                                                                                                                                                                       
  user_defined_symbols: 0                                                                                                                                                                                                                               
  user_defined_symbols: 1                                                                                                                                                                                                                               
  user_defined_symbols: 2                                                                                                                                                                                                                               
  user_defined_symbols: 3                                                                                                                                                                                                                               
  user_defined_symbols: 4                                                                                                                                                                                                                               
  user_defined_symbols: 5                                                                                                                                                                                                                               
  user_defined_symbols: 6                                                                                                                                                                                                                               
  user_defined_symbols: 7                                                                                                                                                                                                                               
  user_defined_symbols: 8                                                                                                                                                                                                                               
  user_defined_symbols: 9                                                                                                                                                                                                                               
  user_defined_symbols: .                                                                                                                                                                                                                               
  user_defined_symbols: !                                                                                                                                                                                                                               
  user_defined_symbols: ?                                                                                                                                                                                                                               
  user_defined_symbols: ```
  user_defined_symbols: <reserved_0>                                                                                                                                                                                                                    
  user_defined_symbols: <reserved_1>                                                                                                                                                                                                                    
  user_defined_symbols: <reserved_2>                                                                                                                                                                                                                    
  user_defined_symbols: <reserved_3>                                                                                                                                                                                                                    
  user_defined_symbols: <reserved_4>
  user_defined_symbols: <reserved_5>
  user_defined_symbols: <reserved_6>
  user_defined_symbols: <reserved_7>
  user_defined_symbols: <reserved_8>
  user_defined_symbols: <reserved_9>
  user_defined_symbols: <reserved_10>
  required_chars: a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z                                                                                                                               
  byte_fallback: 1                                                                                                                                                                                                                                      
  vocabulary_output_piece_score: 1                                                                                                                                                                                                                      
  train_extremely_large_corpus: 0                                                                                                                                                                                                                       
  seed_sentencepieces_file:                                                                                                                                                                                                                             
  hard_vocab_limit: 1                                                                                                                                                                                                                                   
  use_all_vocab: 0                                                                                                                                                                                                                                      
  unk_id: 0                                                                                                                                                                                                                                             
  bos_id: 1                                                                                                                                                                                                                                             
  eos_id: 2                                                                                                                                                                                                                                             
  pad_id: -1                                                                                                                                                                                                                                            
  unk_piece: <unk>                                                                                                                                                                                                                                      
  bos_piece: <s>                                                                                                                                                                                                                                        
  eos_piece: </s>                                                                                                                                                                                                                                       
  pad_piece: <pad>                                                                                                                                                                                                                                      
  unk_surface:  ⁇                                                                                                                                                                                                                                       
  enable_differential_privacy: 0                                                                                                                                                                                                                        
  differential_privacy_noise_level: 0                                                                                                                                                                                                                   
  differential_privacy_clipping_threshold: 0                                                                                                                                                                                                            
}                                                                                                                                                                                                                                                       
normalizer_spec {                                                                                                                                                                                                                                       
  name: identity                                                                                                                                                                                                                                        
  add_dummy_prefix: 1                                                                                                                                                                                                                                   
  remove_extra_whitespaces: 0                                                                                                                                                                                                                           
  escape_whitespaces: 1                                                                                                                                                                                                                                 
  normalization_rule_tsv:                                                                                                                                                                                                                               
}                                                                                                                                                                                                                                                       
denormalizer_spec {} 
```
and pending in here
```
trainer_interface.cc(430) LOG(INFO) Normalizing sentences...
trainer_interface.cc(539) LOG(INFO) all chars count=506211704
trainer_interface.cc(550) LOG(INFO) Done: 99.9% characters are covered.
trainer_interface.cc(560) LOG(INFO) Alphabet size=5840
trainer_interface.cc(561) LOG(INFO) Final character coverage=0.999
trainer_interface.cc(592) LOG(INFO) Done! preprocessed 437308 sentences.
trainer_interface.cc(598) LOG(INFO) Tokenizing input sentences with whitespace: 437308
trainer_interface.cc(609) LOG(INFO) Done! 4317755
```
then exit with error code 139, without any error info
